# Communicating with the community {.unnumbered}

This section will introduce communication practices, resources, and pathways for coordinating work and building effective relationships with other community members.

## The Bioconductor Support Site

The Bioconductor support site is the best place for questions about using Bioconductor packages because the answers are archived, searchable, and can help future users with the same issue.

The site is hosted at <https://support.bioconductor.org>.

## The bioc-devel mailing list

The bioc-devel mailing list is for package development and Bioconductor infrastructure questions, particularly where input from developers or the core team may be needed.

New users can subscribe to the mailing list at <https://stat.ethz.ch/mailman/listinfo/bioc-devel>

## The Bioconductor Chat

Bioconductor uses the open source team chat [Zulip](https://zulip.com/).
The platform is freely accessible.
New users can sign up for at <https://chat.bioconductor.org/>.

::: {.callout-note}
The community previously used Slack for chat, but the transition to Zulip was made to ensure long-term access to discussions and better reflect the community's open-source values.
You can read more about the move from Slack to Zulip - which took place on Monday 2 June 2025 - in the Bioconductor blog post [Bioconductor is Moving from Slack to Zulip for Community Chat](https://blog.bioconductor.org/posts/2025-05-29-slack-to-zulip/).
:::

The Bioconductor Zulip chat is intended for community discussion, brainstorming, coordination, introductions, announcements, mentoring, working group conversations, event planning, and questions that don't naturally fit the support site or bioc-devel.
